### ISSUE TITLE
BOARD_QTI_DYNAMIC_PARTITIONS_PARTITION_LIST

### ISSUE THREAD

**Issue by Hadenix** [masemoel/device_xiaomi_picasso_recovery#6]
`build/make/core/config.mk:905: error: BOARD_QTI_DYNAMIC_PARTITIONS_PARTITION_LIST contains invalid partition name system_ext. Valid names are system vendor product product_services odm.
14:02:11 dumpvars failed with: exit status 1
`

https://github.com/masemoel/device_xiaomi_picasso_recovery/blob/android-11.0_pbrp/BoardConfig.mk#L70

**Comment by masemoel** [comment]
Yes, this is a known issue when compiling Android 11's device tree since Android R comes with a new dynamic partition called **system_ext** 
If you go to that directory, open that file and go to the line 904, you will see a list of all dynamic partitions allowed. Add system_ext to that list and the error should be gone.
Later when you flash the recovery you will see that system_ext mounts perfectly, so it's just a PBRP "non-sense" limitation.

**Comment by masemoel** [comment]
I am going to close this issue as this is Pitch Black's project related and will be fixed for sure with the upcoming Android 11's source release.

**Comment by Hadenix** [comment]
@masemoel ok
